[tool.poetry]
name = "enough lands"
version = "0.0.0"
authors=["owun"]
description = "ai to see if you have enough lands in your magic deck"

[tool.poetry.dependencies]
python = "^3.8"
pandas = "^1.2.4"
numpy = "^1.20.2"
tensorflow = "^2.6.0"
Flask = "^2.0.1"